### ISSUE TITLE
Error CDI/WELD plugin in Wildfly

### ISSUE THREAD

**Issue by diegomon** [HotswapProjects/HotswapAgent#70]
I've been trying to make the last CDI/WELD plugin to work in Wildfly 8.2 but it fails with the following error when I redefine a class.

[31m09:24:44,541 ERROR [stderr] (Thread-236) Exception in thread "Thread-236" java.lang.NoClassDefFoundError: javax/enterprise/inject/spi/AnnotatedType
[0m[31m09:24:44,544 ERROR [stderr] (Thread-236) 	at java.lang.Class.getDeclaredMethods0(Native Method)
[0m[31m09:24:44,544 ERROR [stderr] (Thread-236) 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
[0m[31m09:24:44,545 ERROR [stderr] (Thread-236) 	at java.lang.Class.getDeclaredMethod(Class.java:2120)
[0m[31m09:24:44,545 ERROR [stderr] (Thread-236) 	at org.hotswap.agent.plugin.weld.command.ClassPathBeanRefreshCommand.executeCommand(ClassPathBeanRefreshCommand.java:64)
[0m[31m09:24:44,546 ERROR [stderr] (Thread-236) 	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
[0m[31m09:24:44,547 ERROR [stderr] (Thread-236) Caused by: java.lang.ClassNotFoundException: javax.enterprise.inject.spi.AnnotatedType
[0m[31m09:24:44,547 ERROR [stderr] (Thread-236) 	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
[0m[31m09:24:44,547 ERROR [stderr] (Thread-236) 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[0m[31m09:24:44,548 ERROR [stderr] (Thread-236) 	at java.security.AccessController.doPrivileged(Native Method)
[0m[31m09:24:44,548 ERROR [stderr] (Thread-236) 	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[0m[31m09:24:44,548 ERROR [stderr] (Thread-236) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[0m[31m09:24:44,549 ERROR [stderr] (Thread-236) 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[0m[31m09:24:44,549 ERROR [stderr] (Thread-236) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[0m[31m09:24:44,549 ERROR [stderr] (Thread-236) 	... 5 more

**Comment by skybber** [comment]
As a workaround append **-Djboss.modules.system.pkgs=org.jboss.byteman,org.hotswap.agent** to launch configuration (after hotswap agent options).

**Comment by Darjana** [comment]
Hi,

I'm encountering the same issue with WildFly 8.2 Final, Hotswap Agent 0.3 stable, Eclipse Mars and JBoss Tools. I tried skybber's workaround, but it doesn't seem to change anything for me. I tried e.g. the following vm arguments:

`"-Dprogram.name=JBossTools: WildFly 8.x" -server -Xms2048m -Xmx2048m -XX:MaxPermSize=2048m -Dorg.jboss.resolver.warning=true -Djava.net.preferIPv4Stack=true -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true "-Dorg.jboss.boot.log.file=C:/Users/DELL/Downloads/wildfly-8.2.0.Final/standalone/log/boot.log" "-Dlogging.configuration=file:/C:/Users/DELL/Downloads/wildfly-8.2.0.Final/standalone/configuration/logging.properties" "-Djboss.home.dir=C:/Users/DELL/Downloads/wildfly-8.2.0.Final" -Dorg.jboss.logmanager.nocolor=true -Djboss.bind.address.management=localhost -XXaltjvm=dcevm -javaagent:C:\ProgramFiles\Hotswap\hotswap-agent.jar -Djboss.modules.system.pkgs=org.jboss.byteman,org.hotswap.agent `

(I removed the dedicated -Djboss.modules.system.pkgs parameter, too). Hotswap Agent 0.2 generally works, though. Are there more configuration parameters necessary to use the new Weld plugin?

**Comment by skybber** [comment]
Nope, there is no another parameter. I've tested the CDI plugin on Tomcat. You can disable CDI plugin in hotspap-agent.config  or use 0.2 version temporarily. I'll look on this problem ...

**Comment by skybber** [comment]
you have duplicity in argument definition
-Djboss.modules.system.pkgs=org.jboss.byteman
-Djboss.modules.system.pkgs=org.jboss.byteman,org.hotswap.agent
 I'm not 100% sure the second one overrides the first one.

**Comment by The-Alchemist** [comment]
The ```-Djboss.modules.system.pkgs=org.jboss.byteman,org.hotswap.agent``` suggestion didn't seem to be a valid workaround for me.

**Comment by allstone** [comment]
Try either -Djboss.modules.system.pkgs=org.hotswap.agent,org.jboss.byteman or remove byteman altogether , because byteman might override the agent.

**Comment by The-Alchemist** [comment]
I realized I messed up: my Wildfly had so many JVM flags that I missed that I had already defined ``jboss.modules.system.pkgs``.  However, even if I omit the ``-Djboss.modules....`` complete, I still get the same error.

Is it possible that ``javax/enterprise/inject/spi/AnnotatedType`` is defined in another classloader?

**Comment by skybber** [comment]
I've committed fixes for this issue in the repo. It is still alpha code but it looks it is working. -Djboss.modules.system.pkgs=org.hotswap.agent  is not necesarry since agent internally modifies this parameter.

**Comment by skybber** [comment]
Fixed in repo
